### ISSUE TITLE
`math/rand` is not a secure random number generator

### ISSUE THREAD

**Issue by nelhage** [mittwald/kubernetes-secret-generator#1]
The code uses `math/rand` to generate secrets: https://github.com/mittwald/kubernetes-secret-generator/blob/8e6401a2a3be35d93c0358062fbe09c470ae65f5/main.go#L167-L173

[`math/rand`](https://golang.org/pkg/math/rand/) is a deterministic pseudo-random-number generator, suitable for monte-carlo simulations or other such applications, but **not** a source of secure random numbers. For that purpose you need [`crypto/rand`](https://golang.org/pkg/crypto/rand/).

Any secrets already generated using `math/rand` should be presumed compromised and should be regenerated.

(Note, in particular, that `math/rand` uses a fixed seed across runs, and so such secrets may contain *no* entropy whatsoever. Note that repeated runs of https://play.golang.org/p/MRGyYO_XC6 produced identical secrets)

**Comment by martin-helmich** [comment]
Ouch! Thanks for spotting this, you're absolutely right! Will fix this, soon. :+1:

**Comment by martin-helmich** [comment]
@nelhage I've provided a fix for this in #2. I'd welcome your input on this :)
