### ISSUE TITLE
Password Policy?

### ISSUE THREAD

**Issue by danielnbalasoiu** [mittwald/kubernetes-secret-generator#23]
Can you add the option to configure the exclusion of custom characters?

Thank you!

**Comment by martin-helmich** [comment]
Hey @danielnbalasoiu! Thanks for your suggestion. We already use base64 encoding for generated secrets, which limits the alphabet of generated secrets significantly. Can you describe your use case?

In any way, this is not a feature I see on our roadmap for this project. I'd be happy to review and accept any PRs coming our way regarding this feature, but any implementation of this would probably require a heavy rewrite of the current secret generation workflow (which basically just takes _n_ bytes of random data and pipes it through base64 encoding).

**Comment by day1118** [comment]
Hi @martin-helmich 
I have a use case for this. My secrets sometimes include the `/` symbol which is not accepted by the tool that reads the secret. Is it possible to exclude this (and any) special characters?
Thanks
