### ISSUE TITLE
Option to configure the default encoding for secrets

### ISSUE THREAD

**Issue by lchdev** [mittwald/kubernetes-secret-generator#30]
**Is your feature request related to a problem? Please describe.**
I am systematically using `base64url` encoding to avoid any potential issues with passwords sued in connexion URIs. 

**Describe the solution you'd like**
It would be nice to be able to configure the default encoding, in the same way we can configure the default secret length

**Describe alternatives you've considered**
Currently, I must add the encoding annotation on each secret.

**Comment by vbezhenar** [comment]
Actually it seems that this option exists but not explicitly exposed with helm value. I changed it with the following helm configuration:
```yaml
args:
  - --secret-encoding=base64url
secretLength: 24
```
