### ISSUE TITLE
Release v3.2.0 missing in helm repository

### ISSUE THREAD

**Issue by lchdev** [mittwald/kubernetes-secret-generator#32]
I just noticed that version `3.2.0` is missing from the helm repository. Latest is `3.1.0` in `index.yaml` file.

**Comment by hensur** [comment]
Thanks for the report.
Our chart release workflow seems to have failed for this release.

I just manually regenerated the missing entry in the `index.yaml`.
Please try pulling it again. :slightly_smiling_face:

**Comment by lchdev** [comment]
This is now working fine, thanks ! ;)
