### ISSUE TITLE
Make cluster role creation optional

### ISSUE THREAD

**Issue by day1118** [mittwald/kubernetes-secret-generator#37]
**Is your feature request related to a problem? Please describe.**
I want to limit the scope of secrets-generator to a single namespace & remove the need to create a cluster role

**Describe the solution you'd like**
Add a variable such as `rbac.create` & `rbac.clusterRole` which disable the `role` and `clusterRole` respectively. Both would default to `true` for backwards compatibility.

If `rbac.clusterRole` is `false`, then `watchNamespace` should default to `{{ .Release.Namespace }}` as the generator will not have permissions to access other namespaces.

**Describe alternatives you've considered**
`WATCH_NAMESPACE` could be updated to include the `tpl` function so that it can be set to `{{ .Release.Namespace }}` via the values file, but this doesn't remove the `clusterRole`
```
env:
  - name: WATCH_NAMESPACE
    value: {{ tpl .Values.watchNamespace . }}
```
**Additional context**
I can raise a PR for these changes if you are happy with the variable names. 
Concept modelled from [bitnami/external-dns](https://github.com/bitnami/charts/blob/a9c99d4043e64372dc4a657039f2e36b18a985a5/bitnami/external-dns/values.yaml#L584-L588)

**Comment by day1118** [comment]
Are you able to review the PR please @YannikBramkamp ?

**Comment by day1118** [comment]
@YannikBramkamp @martin-helmich 
Can you please cut a release with this change included?
Thanks

**Comment by YannikBramkamp** [comment]
Done @day1118

**Comment by day1118** [comment]
Thanks @YannikBramkamp - there was no helm release generated for `3.3.0` - Can you please trigger this?

**Comment by YannikBramkamp** [comment]
@day1118 Sorry for the delay, Should be available now
