### ISSUE TITLE
Pod connection refused with Liveness and Readiness

### ISSUE THREAD

**Issue by n1vgabay** [mittwald/kubernetes-secret-generator#65]
Hi,

Just applied your chart on my k8s cluster 1.21 version.

Everything went fine until the log of the deployment itself sends this message:

Liveness probe failed: Get "http://10.0.171.162:8080/healthz": dial tcp 10.0.171.162:8080: connect: connection refused
Readiness probe failed: Get "http://10.0.171.162:8080/readyz": dial tcp 10.0.171.162:8080: connect: connection refused

I'll be happy for some assist about that.

Thanks!

**Comment by martin-helmich** [comment]
Sorry for the late response. Is the Pod actually running? Any suspicious log output from the container?
