### ISSUE TITLE
Add support for wireguard keys

### ISSUE THREAD

**Issue by telmich** [mittwald/kubernetes-secret-generator#67]
**Is your feature request related to a problem? Please describe.**

If one wants to run Wireguard VPN servers, they need keys generated by `wg genkey`.

**Describe the solution you'd like**

A new annotation to support wireguard keys

**Describe alternatives you've considered**

Using a normal password and feeding it as a seed to `wg genkey`, however `wg genkey` does not support any parameters.

**Additional context**

This is very similar to ssh keys as the application is also pub/private key.
For the format/verification see my last message on https://lists.zx2c4.com/pipermail/wireguard/2020-December/006221.html

**Comment by hensur** [comment]
I guess one could just use https://github.com/WireGuard/wgctrl-go/blob/bd2cb7843e1b98193f01eb288793e741a814a269/wgtypes/types.go#L89 to generate a public and private key, and optionally a pre-shared key as well.
