### ISSUE TITLE
Backwards compatibility broken because of CRDs

### ISSUE THREAD

**Issue by ptcar2009** [mittwald/kubernetes-secret-generator#71]
**Describe the bug**
Previously, the deployment would work with just tag based secret injection, but after the CRDs were introduced, it's impossible to use it without CRDs installed.

**To Reproduce**
Deploy the helm-chart with the flag `skip-crds` and try to inject a secret.
**Expected behavior**
The pod would detect or at least there would be a configuration which would make the deployment work.

**Environment:**
 - Kubernetes version: v1.21.5
 - kubernetes-secret-generator version: >=v3.3.3

**Comment by day1118** [comment]
Hi @martin-helmich 
We have raised [#70](https://github.com/mittwald/kubernetes-secret-generator/pull/70) to address this issue. Can you please review & merge it? 
Thanks

**Comment by martin-helmich** [comment]
> Hi @martin-helmich 
> 
> We have raised [#70](https://github.com/mittwald/kubernetes-secret-generator/pull/70) to address this issue. Can you please review & merge it? 
> 
> Thanks

Apologies for the late response. I'll take a look shortly. 👀
