### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by antoniomrfranco** [mittwald/kubernetes-secret-generator#74]
Could anyone please cut a release to generate a new image tag with the latest fixes?

**Comment by day1118** [comment]
Hi @martin-helmich - can you please cut the release?
Thanks

**Comment by martin-helmich** [comment]
Sorry for the late reaction -- [here you go](https://github.com/mittwald/kubernetes-secret-generator/releases/tag/v3.4.0). 🙂
