### ISSUE TITLE
flag provided but not defined: -regenerate-insecure

### ISSUE THREAD

**Issue by japsu** [mittwald/kubernetes-secret-generator#8]
It seems that the version of `kubernetes-secret-generator` hosted at `quay.io/mittwald/kubernetes-secret-generator` does not support the `-regenerate-insecure` parameter. Is the image outdated?

See [this gist](https://gist.github.com/japsu/204d5140d5d39f47e7d878071af9e2b3).

**Comment by japsu** [comment]
Built from `HEAD`, pushed it in [Docker Hub](https://hub.docker.com/r/tracon/kubernetes-secret-generator/), swapped the image in `secret-generator.yaml`, works.

**Comment by japsu** [comment]
@martin-helmich even after the recent merge of #9 this problem still persists. I take it there is no automated build process that would update the image in quay.io? Would it be possible to make one using eg. Travis CI?

**Comment by Hermsi1337** [comment]
Hey @japsu,   
sorry for our - very late - answer. We published a new version of the secret generator yesterday.    

We will do some refactoring on this project and modify the "image-pushing-thing" a bit.   
Behold (:

Regards,
Hermsi

**Comment by japsu** [comment]
Hi @Hermsi1337! Thank you for your continued work on a very useful tool. I'll check out the new version!
