### ISSUE TITLE
Is this project still in active development?

### ISSUE THREAD

**Issue by mattmattox** [mittwald/kubernetes-secret-generator#98]
This image popped up during a CVE scan and it looks like the last release was 2 years ago. I would like to submit some PRs to bump the GO versions to more updated versions.

**Comment by martin-helmich** [comment]
Hey Matthew; 👋  this project is _not_ abandoned, although I will admit that lately it hasn't received the attention it should have. I'll happily review any PRs coming our way, and can also tag a new release when required. 😄

**Comment by mattmattox** [comment]
Awesome, I'm currently working on a [PR79](https://github.com/mittwald/kubernetes-secret-generator/pull/97) to bump to GO 1.16.

I'm working through a test issue (make crd is throwing an error) https://github.com/mittwald/kubernetes-secret-generator/actions/runs/8512654950/job/23330345719?pr=97
